name: CI
on: [push]
jobs:
  build:
    run-on: ubuntu-latest
    step:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build